# Generated by Django 2.2.2 on 2019-06-12 17:29

from django.db import migrations, models
import sweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=sweets.models.image_folder),
        ),
    ]
