# Generated by Django 2.2.2 on 2019-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0004_auto_20190612_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
