from .base_view import base_view
from .product_view import product_view
from .category_view import category_view
from .cart_view import cart_view
from .add_to_cart_view import add_to_cart_view
from .remove_from_cart_view import remove_from_cart_view
from .change_item_qty import change_item_qty
from .checkout_view import checkout_view
from .order_create_view import order_create_view
from .make_orer_view import make_order_view
from .account_view import account_view
from .registration_view import registration_view
from .login_view import login_view